# This rule is not used by the project istio-qos itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mesh.knabben.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: istio-qos
    app.kubernetes.io/managed-by: kustomize
  name: podlabelerpolicy-admin-role
rules:
- apiGroups:
  - mesh.knabben.github.com
  resources:
  - podlabelerpolicies
  verbs:
  - '*'
- apiGroups:
  - mesh.knabben.github.com
  resources:
  - podlabelerpolicies/status
  verbs:
  - get
