apiVersion: mesh.knabben.github.com/v1alpha1
kind: PodLabelerPolicy
metadata:
  labels:
    app.kubernetes.io/name: istio-qos
    app.kubernetes.io/managed-by: kustomize
  name: podlabelerpolicy-sample
spec:
  # TODO(user): Add fields here
